Hw02 express
VolodymyrSkaskiv/nodejs-homework-rest-api pull request #1
Opened 2023-07-05 20:09 UTC by VolodymyrSkaskiv

2023-07-05 20:11 UTC, VolodymyrSkaskiv commented
перевірте домашку

2023-07-06 07:21 UTC, KhYulian commented on controllers/contacts.js
> +  const list = await contactsMethods.listContacts(); // Виклик методу listContacts модуля contactsMethods для отримання списку контактів
```suggestion
  const list = await contactsMethods.listContacts(); 
```

2023-07-06 07:21 UTC, KhYulian commented on controllers/contacts.js
> +  const list = await contactsMethods.listContacts(); // Виклик методу listContacts модуля contactsMethods для отримання списку контактів
приберіть усі надлишкові коменти. В крайньому разі пишіть їх англійською

2023-07-06 07:22 UTC, KhYulian commented on helpers/CtrlWrapper.js
> +  return func; // Повернення обгортки контролера
```suggestion
return async (req, res, next) => {
    try {
      await ctrl(req, res, next);
    } catch (error) {
      next(error);
    }
  };
```

2023-07-06 07:22 UTC, KhYulian commented on helpers/HttpErrors.js
> +const HttpErrors = (status, message) => {
Використовуйте класи. В slack можете знайти приклад

2023-07-06 07:22 UTC, KhYulian requested changes
Потрібні правки

2023-07-13 19:05 UTC, VolodymyrSkaskiv commented on controllers/contacts.js
> +  const list = await contactsMethods.listContacts(); // Виклик методу listContacts модуля contactsMethods для отримання списку контактів
Забрав коменти, переписав через клас

2023-07-14 07:19 UTC, KhYulian approved these changes
Чудова робота

2023-07-14 07:19 UTC, merged